---
name: Build
run-name: ${{ github.actor }} is building
on: [push]
jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build wireguard exporter x86
        run: |
          sudo apt-get update
          sudo apt-get install golang-go -y
          cd cmd/wireguard_exporter/
          go build .
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: wireguard_exporter_x86
          path: cmd/wireguard_exporter/wireguard_exporter
